[package]
name = "databaser"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = "0.32.1"
clap = { version = "4.5.21", features = ["derive"] }
serde = { version = "1.0.215", features = ["derive"] }
toml = "0.8.19"
csv = "1.3.1"
